# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('creator', models.CharField(max_length=64)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
